# Generated by Django 5.1 on 2024-09-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='apply_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='details_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
