# Generated by Django 5.1 on 2024-09-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobapplication_delete_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('interview', 'Interview'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
