# Generated by Django 5.1 on 2024-09-04 14:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_career_apply_link_alter_career_details_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='full_description',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
    ]
